### PR TITLE
Updated files to add 1254 more icons

### PR DESCRIPTION
**Pull request by raulmabe**
I noticed there were some icons in the [official web](https://phosphoricons.com/) (i.e. `graduation_cap`) I intended to use in my app, so I updated the source icon files and rerun the script to add 418 icons, with a total of 1254 icon variations.

I check on the `example/` app if the new ones work and they do

### CODE REVIEW

**Comment by afkcodes** [comment]
Thanks @raulmabe This is pretty cool. just testing it out on my side and merging it. Thanks again.

**Comment by afkcodes** [comment]
seems like scss has also been added it was not there, when i created this package.

**Comment by raulmabe** [comment]
So the `.scss` file was there, but I deleted the old one and inserted an updated `.css`

**Comment by afkcodes** [comment]
@raulmabe can you just format the dart file seems like formatting if off.

**Comment by raulmabe** [comment]
Yeah it was off, I will push the formatted version. Also I noticed there are some weird icons in the source file `phosphor-codes.css` I downloaded from their website that are not on the website... (i.e. `PhosphorIcons.SF400000`)

 I am doing some testing with them at the moment... Maybe we'll need to delete them

**Comment by afkcodes** [comment]
gotcha, may be because the changes in script it is happening please check the script and try to use scss, i personally don't think we need to change anything in script.

**Comment by raulmabe** [comment]
The script works well. The "problem" is that the new .css file carries some glyphs like [this one](http://www.eki.ee/letter/chardata.cgi?ucode=250C). These glyphs **do not** have different tones, however I think they may be useful to some people working with algebra or others.

**Comment by afkcodes** [comment]
@raulmabe it seems i am unable to check your branch some issue from my side can you please confirm if all things are right and good to go ?

**Comment by raulmabe** [comment]
What issues do you have encountered? I am using my fork in one of my projects and I am not having any issue

**Comment by afkcodes** [comment]
its not related to the the repo its github seems like some mis-configuration has happened.

**Comment by afkcodes** [comment]
Merged & Updated at pub.dev Thanks @raulmabe

**Pull request merged**
